language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

git:
  depth: 2

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

before_install:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer selfupdate

install:
  - composer update --prefer-source --no-interaction

script:
  - composer test
  - composer cs-test

notifications:
  email:
    - saunier.johann@gmail.com
